# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "homula-camp-app"
client_id = "a8afb1ab2ec6bc948536795b73e19062"
application_url = "https://investors-accessing-role-gale.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers"

[auth]
redirect_urls = [
  "https://investors-accessing-role-gale.trycloudflare.com/auth/callback",
  "https://investors-accessing-role-gale.trycloudflare.com/auth/shopify/callback",
  "https://investors-accessing-role-gale.trycloudflare.com/api/auth/callback",
  "https://investors-accessing-role-gale.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "homula-camp-2.myshopify.com"
